import fetch from 'node-fetch';
import * as dotenv from 'dotenv';
dotenv.config();

const { TENSOR_TOKEN } = process.env;
console.log(TENSOR_TOKEN);

const TENSOR_API_URL = 'https://graphql.tensor.trade/graphql';

export const unfavTensorNFT = async (mintId: string): Promise<UnfavTensorNFTResponse> => {
  const result = await fetch(TENSOR_API_URL, {
    headers: {
      accept: '*/*',
      'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7',
      'cache-control': 'no-cache',
      'content-type': 'application/json',
      pragma: 'no-cache',
      'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'x-request-id': '52bc78f7-6f3a-4214-9337-8a0a3a73c5f2',
      Referer: 'https://www.tensor.trade/',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
    body: JSON.stringify([
      {
        operationName: 'RemoveFavMint',
        variables: {
          mint: mintId,
          jwt: TENSOR_TOKEN,
        },
        query:
          'mutation RemoveFavMint($jwt: String!, $mint: String!, $favList: Int) {\\n  removeFavMint(jwt: $jwt, mint: $mint, favList: $favList)\\n}',
      },
    ]).replace(/\\\\/g, '\\'),
    method: 'POST',
  }).then((response) => response.json() as Promise<UnfavTensorNFTResponse>);

  handleErrors(result);
  return result;
};

export const favTensorNFT = async (mintId: string): Promise<FavTensorNFTResponse> => {
  const result = await fetch(TENSOR_API_URL, {
    headers: {
      accept: '*/*',
      'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7',
      'cache-control': 'no-cache',
      'content-type': 'application/json',
      pragma: 'no-cache',
      'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'x-request-id': 'f0d2a510-4f17-476f-82b4-4a9da5955ddd',
      Referer: 'https://www.tensor.trade/',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
    body: JSON.stringify([
      {
        operationName: 'AddFavMint',
        variables: {
          mint: mintId,
          jwt: TENSOR_TOKEN,
        },
        query:
          'mutation AddFavMint($jwt: String!, $mint: String!, $favList: Int) {\\n  addFavMint(jwt: $jwt, mint: $mint, favList: $favList)\\n}',
      },
    ]).replace(/\\\\/g, '\\'),
    method: 'POST',
  }).then((response) => response.json() as Promise<FavTensorNFTResponse>);

  handleErrors(result);
  return result;
};

export const getTensorFavNFTsForWallet = async (walletId: string): Promise<string[]> => {
  const result = await fetch(TENSOR_API_URL, {
    headers: {
      accept: '*/*',
      'accept-language': 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7',
      'cache-control': 'no-cache',
      'content-type': 'application/json',
      pragma: 'no-cache',
      priority: 'u=1, i',
      'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-site',
      'x-request-id': 'b9a9487e-3bed-4a7a-869b-bfbded3c4db2',
      Referer: 'https://www.tensor.trade/',
      'Referrer-Policy': 'strict-origin-when-cross-origin',
    },
    body: JSON.stringify([
      {
        operationName: 'UserProfileV2',
        variables: {
          wallet: walletId,
          jwt: TENSOR_TOKEN,
        },
        query:
          'query UserProfileV2($wallet: String!, $jwt: String!) {\\n  userProfileV2(wallet: $wallet, jwt: $jwt) {\\n    ...ReducedUserProfile\\n    __typename\\n  }\\n}\\n\\nfragment ReducedUserProfile on UserProfile {\\n  id\\n  genesisWallet\\n  username\\n  pfp\\n  twitter\\n  twitterFollowed\\n  discord\\n  discordJoined\\n  email\\n  emailConfirmed\\n  referralCode\\n  referrer\\n  referees {\\n    wallet\\n    rank7d\\n    rankTotal\\n    __typename\\n  }\\n  wallets {\\n    wallet\\n    __typename\\n  }\\n  favWallets {\\n    address\\n    label\\n    __typename\\n  }\\n  favCollections {\\n    slug\\n    favList\\n    __typename\\n  }\\n  favMints {\\n    mint\\n    __typename\\n  }\\n  airdropOne {\\n    ...AirdropOneFields\\n    __typename\\n  }\\n  airdropFour {\\n    ...AirdropThreeProfileStats\\n    __typename\\n  }\\n  loyaltyLevel\\n  bidNotifMinPctFloor\\n  airdropTwoRewards {\\n    ...AirdropTwoFields\\n    __typename\\n  }\\n  stakedTensorians {\\n    ...StakedTensoriansFields\\n    __typename\\n  }\\n  ptsStakingTotal\\n  ptsStaking7d\\n  __typename\\n}\\n\\nfragment AirdropOneFields on AirdropOne {\\n  volume\\n  totalTensorPoints\\n  eligibleSpecialBoxes\\n  completedListing\\n  completedBid\\n  completedAirdrop\\n  claimedBoxes {\\n    nftBoxCommon\\n    nftBoxUncommon\\n    nftBoxRare\\n    nftBoxEpic\\n    nftBoxLegendary\\n    tokenBoxCommon\\n    tokenBoxUncommon\\n    tokenBoxRare\\n    tokenBoxEpic\\n    tokenBoxLegendary\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment AirdropThreeProfileStats on AirdropThreeProfileStats {\\n  rank7d\\n  rankTotal\\n  wallet\\n  loyalty\\n  __typename\\n}\\n\\nfragment AirdropTwoFields on AirdropTwo {\\n  claimedBoxes {\\n    nftBoxCommon\\n    nftBoxUncommon\\n    nftBoxRare\\n    nftBoxEpic\\n    nftBoxLegendary\\n    tokenBoxCommon\\n    tokenBoxUncommon\\n    tokenBoxRare\\n    tokenBoxEpic\\n    tokenBoxLegendary\\n    __typename\\n  }\\n  __typename\\n}\\n\\nfragment StakedTensoriansFields on StakedTensorians {\\n  totalSupply\\n  stakedSupply\\n  stakedNfts {\\n    ...ReducedMintWithColl\\n    __typename\\n  }\\n  stakedLevel\\n  activatedLevel\\n  overridenLevel\\n  nftsForNextLevel\\n  pfp\\n  __typename\\n}\\n\\nfragment ReducedMintWithColl on MintWithColl {\\n  ...ReducedMint\\n  collName\\n  slug\\n  slugDisplay\\n  numMints\\n  __typename\\n}\\n\\nfragment ReducedMint on TLinkedTxMintTV2 {\\n  onchainId\\n  compressed\\n  owner\\n  name\\n  imageUri\\n  animationUri\\n  metadataUri\\n  metadataFetchedAt\\n  files {\\n    type\\n    uri\\n    __typename\\n  }\\n  sellRoyaltyFeeBPS\\n  tokenStandard\\n  tokenEdition\\n  attributes {\\n    trait_type\\n    value\\n    __typename\\n  }\\n  lastSale {\\n    price\\n    txAt\\n    __typename\\n  }\\n  accState\\n  hidden\\n  ...MintRarityFields\\n  staked {\\n    stakedAt\\n    activatedAt\\n    stakedByOwner\\n    __typename\\n  }\\n  inscription {\\n    ...InscriptionData\\n    __typename\\n  }\\n  tokenProgram\\n  metadataProgram\\n  transferHookProgram\\n  listingNormalizedPrice\\n  hybridAmount\\n  __typename\\n}\\n\\nfragment MintRarityFields on TLinkedTxMintTV2 {\\n  rarityRankHrtt\\n  rarityRankStat\\n  rarityRankTeam\\n  rarityRankTn\\n  __typename\\n}\\n\\nfragment InscriptionData on InscriptionData {\\n  inscription\\n  inscriptionData\\n  immutable\\n  order\\n  spl20 {\\n    p\\n    tick\\n    amt\\n    __typename\\n  }\\n  __typename\\n}',
      },
    ]).replace(/\\\\/g, '\\'),
    method: 'POST',
  }).then((response) => response.json() as Promise<GetTensorFavNFTsForWalletReponse>);

  handleErrors(result);
  return result[0].data.userProfileV2.favMints.map((item) => item.mint);
};

const handleErrors = (result: any): void => {
  if ((result as TensorError)[0]?.errors?.[0]?.message === 'jwt expired') {
    throw new Error('jwt expired');
  }
};

type TensorError = typeof tensorError;
const tensorError = [
  {
    errors: [
      {
        message: 'jwt expired',
        locations: [{ line: 2, column: 3 }],
        path: ['userProfileV2'],
        extensions: { code: 'INTERNAL_SERVER_ERROR' },
      },
    ],
    data: { userProfileV2: null },
  },
];

// -----

const favNftsForWalletResult = [
  {
    data: {
      userProfileV2: {
        id: '6883f50b-d333-4768-a67c-410da0da8e7d',
        genesisWallet: 'Et6B96uSx2wSGLSdj95q1iYncpf43tTPU2mWvCv5s9Ad',
        username: null,
        pfp: null,
        twitter: null,
        twitterFollowed: false,
        discord: null,
        discordJoined: false,
        email: null,
        emailConfirmed: false,
        referralCode: null,
        referrer: null,
        referees: [],
        wallets: [
          { wallet: 'Et6B96uSx2wSGLSdj95q1iYncpf43tTPU2mWvCv5s9Ad', __typename: 'UserWallet' },
          { wallet: '3PncMbC3Zn1ZDd4Cwa8GGHo4S5Ba3ajqkKG6yJw8JE6x', __typename: 'UserWallet' },
        ],
        favWallets: [],
        favCollections: [
          { slug: 'cets_on_creck', favList: 1, __typename: 'CollectionFavorite' },
          { slug: 'shadowy_super_coder_dao', favList: 1, __typename: 'CollectionFavorite' },
        ],
        favMints: [
          { mint: '22bEJjheBGeYPDwyz1Z9JoGuhU8Si35urZUPpJHDFwTn', __typename: 'MintFavorite' },
          { mint: '23Wx3bmnj4eNc6nYBoWrWtgL2MKUTtH8KyZGoyYpFfjj', __typename: 'MintFavorite' },
          { mint: '24Dr9z57P6e665w7NiV9ZV4czXLh5ybYKizi2H9Zb7kA', __typename: 'MintFavorite' },
          { mint: '28m1qmGJXxdY2MgZH7nVi3B97xzLhbuZBdrEievLfgH7', __typename: 'MintFavorite' },
          { mint: '2aiuhvcqEiLD1tEtxxNsL93eNPKFRivPpBckEC8rZvX2', __typename: 'MintFavorite' },
          { mint: '2apZJYRsUTUMzswFPCg8Jb5vang2tyi3a7jHw8p5T19i', __typename: 'MintFavorite' },
          { mint: '2djff8kNbujgp2vz8a7VRSkE36A3AXMqH8bndjAcYWcc', __typename: 'MintFavorite' },
          { mint: '2FmWFnwejv6QDefRvVV4eBAJAJLnCJJFGyTvZStCwLnP', __typename: 'MintFavorite' },
          { mint: '2gbvUsrpovmiQou8QxHooM6LSaP5Uakq3tgSNPuwEZSS', __typename: 'MintFavorite' },
          { mint: '2GY8qKSNjN66wYxRUpGxg7PMr3XsW4J6k13Qoby2S4Mf', __typename: 'MintFavorite' },
          { mint: '2p9V9MHoxjezGFyCq5eSmVgG8YChMsybhHXiwXWfSxoZ', __typename: 'MintFavorite' },
          { mint: '2w6vNNoFjQgZZhUv3pnoqsaVtJaK1Vd2o6DUmXCxZqGy', __typename: 'MintFavorite' },
          { mint: '2xDZuCvzrkrkVSkN42XEkWfvgGugbs413hGDvJjndgjZ', __typename: 'MintFavorite' },
          { mint: '2xVuqZYokjXQp4Px2TqfynHtskLnoLboAF6tHTSsMLQo', __typename: 'MintFavorite' },
          { mint: '33K9XjDNarYYSHCyBsfXUSGGpG1qnqHCT9dFNnCqwxSJ', __typename: 'MintFavorite' },
          { mint: '3aC9xurLX5WM4vRhrhaVh5TTEKiynYbak1wiKHmBQwWa', __typename: 'MintFavorite' },
          { mint: '3CEvgX8RHZ8bJ1R9i4u6gzKdDG1LLbJE6TCPCmeUo3TX', __typename: 'MintFavorite' },
          { mint: '3dW9dKjYYjnjaeWj12EbXmy7nY7bsdVELocg14k7azeL', __typename: 'MintFavorite' },
          { mint: '3EZhG8Nqsh8Fmfcv4D84779PHKyZ6YnBVRPkQLSQ4Jtj', __typename: 'MintFavorite' },
          { mint: '3FpZaHxkUoRMYBGwePyNH73QQjvG6gLDpLvkp6MoX8Xt', __typename: 'MintFavorite' },
          { mint: '3GCodZG9hgUrPsMbFoDc5gDSveY3m3W6UxUxB1Ah9XeB', __typename: 'MintFavorite' },
          { mint: '3HxdFEEYtJjvXEZCQemQV4NvMXYv9kWoTCaG6upksxmc', __typename: 'MintFavorite' },
          { mint: '3nC4qae9AbENGy9ZuSGE5r2Fu5BUM3rGGA7EW73cjX6d', __typename: 'MintFavorite' },
          { mint: '3pdDpSRHrvWcfM7FeRweSXYP9xFVc4FoRiiYvonoZsGc', __typename: 'MintFavorite' },
          { mint: '3UYfFzHqNNffe17ccPjc7aAHUDW7qNvbmKhAK8qrY5Fu', __typename: 'MintFavorite' },
          { mint: '3ViswZ43bSQeKXi5tHRjoW2wwxTWVXw9ZZSysxTLVcdj', __typename: 'MintFavorite' },
          { mint: '3Wq98Kq1QmqZYH7mr4AQRPL63Tqhp5XGe1ueVjo85PcN', __typename: 'MintFavorite' },
          { mint: '3xcXiURvAwUzj4rGsj6QWBuiGDqVrVswD4iRs9oQWfru', __typename: 'MintFavorite' },
          { mint: '3XebrT4MsydhT49RhS8dA1Wca51MuWgtwoKA5gyPCTkY', __typename: 'MintFavorite' },
          { mint: '3ZySVMPRwU5C6n1ubw1PduqFbBhYBhXwBz2mRX7SCNQ3', __typename: 'MintFavorite' },
          { mint: '46u45F6nPmKT9ETiALuV2cZm9Seoac6gFSesKLAsPgfr', __typename: 'MintFavorite' },
          { mint: '47C4cP1PXBqE6cPmb2aHatBSCnd2oVBbmywDCL2Pszcg', __typename: 'MintFavorite' },
          { mint: '48SCtZVPzAc3cDqnEGAnkJAeS1hdmMcgu3Ke1XUZJxfY', __typename: 'MintFavorite' },
          { mint: '4BRngh4sGAy3Vb8CCZJqZbAnZBbv66z9h5HQaxQZkJV4', __typename: 'MintFavorite' },
          { mint: '4bvaAr63dGDbomJTsMCMUgWVLyUn1ugnbGfJqoY9gQRA', __typename: 'MintFavorite' },
          { mint: '4CfogbGA2Pjtpo9rW5TJouKB1zdb51hugfyihHHrEmEM', __typename: 'MintFavorite' },
          { mint: '4cSbueohYy3fgGe8KUBe7tonxuQvUayxv9iXy3BGpndL', __typename: 'MintFavorite' },
          { mint: '4dDLkwDrKGBLP9La4WuuhXu2aJ426RXhbxUcksar9AbS', __typename: 'MintFavorite' },
          { mint: '4EPS5fJD3XPSQTL4Le1cV3jJFNyLuCt8tvQtnPbeth1T', __typename: 'MintFavorite' },
          { mint: '4G1Hhgd8MCwfMwTJStPuRjYTG983xvYmCWi2k6pQSjMc', __typename: 'MintFavorite' },
          { mint: '4HniF4cjb2EDBMLVTXwBPZNLQsyTLGcFZaQffN4xJ2Ps', __typename: 'MintFavorite' },
          { mint: '4iX48KxfiMQdkvvLmQ4wvBY3SATrwjq1xMc8o4BuBTwn', __typename: 'MintFavorite' },
          { mint: '4kzDV1toDZhivHm9rnyg1HzPmFW7dcRVcnMM4THaUAss', __typename: 'MintFavorite' },
          { mint: '4Mhcn41hVH4xLtHBSAmS3ejdJgM4LViNeZkDcgMbu6cZ', __typename: 'MintFavorite' },
          { mint: '4oq5da35bgMGWb6yPHtNsojiB7RGUiNyfRwvCVvAfpJt', __typename: 'MintFavorite' },
          { mint: '4pcA4dwQsK1nQM7Sg4AUPccR91SkZdQRBqHgzKHww13t', __typename: 'MintFavorite' },
          { mint: '4pfU2NY4EReVnxCW4QN5z5MpijKR6Poy1nXfeiU1VAQJ', __typename: 'MintFavorite' },
          { mint: '4SWhpJ34ZZPStJyLY347cVjEs7GzrEnxywir3S9rukCo', __typename: 'MintFavorite' },
          { mint: '4Vi3qpaec322F6rJwsCUFEQUb6heY4NhGXkjpnpaB3pt', __typename: 'MintFavorite' },
          { mint: '4Vp5ii4PqNbWmfwj4i14CmijTmBtprd1CA3t2UDipkb3', __typename: 'MintFavorite' },
          { mint: '4VYNQLwDJEGSmak1JWLwZcSgWs92P8sYcYNfrxmb4P2A', __typename: 'MintFavorite' },
          { mint: '4zeDJgc2fSrBH3LLHL3ifoYrBfp2R2Vk6sRKQTXKHuQW', __typename: 'MintFavorite' },
          { mint: '51T85uKXQVjeDM41t1cYWgmW6ipMWrwzNsbEEyyjQm7x', __typename: 'MintFavorite' },
          { mint: '51w22TNWv5ExzaQYyb5j4U2RT1qC8uafPYCD3YSvgrHF', __typename: 'MintFavorite' },
          { mint: '5B5vox49UBvdKFg6c37n7McvABbxTvBRxKekTYM1coa3', __typename: 'MintFavorite' },
          { mint: '5CmJxKKs8bsfaipXGxGmNekpgcnwa3ysQtGTJZrhFHqj', __typename: 'MintFavorite' },
          { mint: '5CwMw4Ky1KDNHhJJDoCrcA9g87fGHBTyGhmsfQjxNMdJ', __typename: 'MintFavorite' },
          { mint: '5Dcb2wcoxbFbsKsNwiUd43GFWcKRjkEm2Y88ubaVigQz', __typename: 'MintFavorite' },
          { mint: '5eaB5YiKxGzER4GZKcTPJuVPf3ayCffteemzWTZY71GW', __typename: 'MintFavorite' },
          { mint: '5hXj5Co5so23Hs7S4kSAPaBXMUBRkZkPWBJDLnNJoRTu', __typename: 'MintFavorite' },
          { mint: '5kLqeBNhcDtycnkVJWkGmKa4njLpYWTDw7RZkskevra', __typename: 'MintFavorite' },
          { mint: '5o9NaBuHoWNYv6gyPbaRwy8Pez9eiG2LCVbNQu3n13Vf', __typename: 'MintFavorite' },
          { mint: '5Q68To9QBtheQfDvTGRo1meoehkktX7Ycep7Nq2uXcG5', __typename: 'MintFavorite' },
          { mint: '5QFF2Xh7Dnn8dzBFLyAZ3Ytrp2jdBDEqPn277FH98HVf', __typename: 'MintFavorite' },
          { mint: '5TkhoCrbucKHyYqHAiAaSfSBDmHGWCBDeMQaWWKc89AH', __typename: 'MintFavorite' },
          { mint: '5wEvCHLRUdezRFRKcJTLRLKdAF1Z9uhvV9SsQ5NiyGnG', __typename: 'MintFavorite' },
          { mint: '66PmpJvG6xFKT4WEH1cuRfMbMFaH5dCYXH7UiVYDrvp6', __typename: 'MintFavorite' },
          { mint: '67agHDPGdCDqkji1A9MDdYfnNndYnoQvKqSyze5AE7TP', __typename: 'MintFavorite' },
          { mint: '694zVGawqj81whRMgHPwGY7bW3TN5TBri3PkUdkWwCse', __typename: 'MintFavorite' },
          { mint: '69VnvafCvXEEmPdyxLoP5N2AC3ryoK6hvh1JYzWdLLHg', __typename: 'MintFavorite' },
          { mint: '6B2R4KkyPed2tobTyCds3fgxdLCia9weu6eUfjpdEwgy', __typename: 'MintFavorite' },
          { mint: '6CLWEvYu1eciQgRyKRyxyCvBApebmFpN6d5nGmu12CQH', __typename: 'MintFavorite' },
          { mint: '6D3A5tmWdd5UodVtCVzoWm2aRcHjGaEpHmFz6jmQsfzJ', __typename: 'MintFavorite' },
          { mint: '6hNtP4MeuCehnKPu46Jk3LV4ttMxB4CTSoYDyoHecyUt', __typename: 'MintFavorite' },
          { mint: '6j7XQyp8cRnfZqcc6UMnuUKgnahrhbW3BYPM3FTL7NRz', __typename: 'MintFavorite' },
          { mint: '6k2erUzECsDaANTdeKYH1zyNEKdN4X1hFDfZjjEPr24Q', __typename: 'MintFavorite' },
          { mint: '6LW1GTNSsmyncVLfiZerk5PVK3MfTHeFNP2WWvUXkEem', __typename: 'MintFavorite' },
          { mint: '6Mmqdn1kF7YiXf5so3CBmH4wuXrrbdnTZTuhi4Ao2sqD', __typename: 'MintFavorite' },
          { mint: '6Q4xcUfeZquJoq3112HTMjQoQwDbSeiTDciWrE98Mxby', __typename: 'MintFavorite' },
          { mint: '6Rhrseas7pvv1S5vB8RPGB1swU2qnmhuS9X5FH9GewRS', __typename: 'MintFavorite' },
          { mint: '6UDdCzNxZFnpRm8kiXpqdv4Ygdj93vB3noAGGSaT8XAZ', __typename: 'MintFavorite' },
          { mint: '6Yr9GynNdgraVB4L1EKhuPAXNAvYrrS2Sj7Nphh4wx5d', __typename: 'MintFavorite' },
          { mint: '6yZxXofZc5CHex9rA7tKsLarNifVxyWxSsU69nz2c1Kq', __typename: 'MintFavorite' },
          { mint: '6zy158fAMRS3Unc2MfnzPRXKRYT85BUHpcVp5GjfF8C2', __typename: 'MintFavorite' },
          { mint: '73u3naVjCcP3Ng4T9nHERgxd145e5kWSLBg4tqea9bU6', __typename: 'MintFavorite' },
          { mint: '74jZbrCibU1AxdJ1EPUJPK1F1N8aFb5KoKwf54oBNWJM', __typename: 'MintFavorite' },
          { mint: '75LNisF7fyueG4PH5eDU3vZyo8ikr7iw11eeNsnNQq1F', __typename: 'MintFavorite' },
          { mint: '78UP5ismEg9697ak5wCysWXcPksa2D1httiSyz2gH1z1', __typename: 'MintFavorite' },
          { mint: '7AnjeRnVyEGU8uz8CqtGQpSzkZ8nXaNTfDsA13n2A5YT', __typename: 'MintFavorite' },
          { mint: '7AwvVS6HyoTZFpiojvEZ5hdLyVr814J7byp7wE3KRt6i', __typename: 'MintFavorite' },
          { mint: '7b7mEcWQSMmFATSJixkpNgFLjBj53WCkkKNHU2fHWdrj', __typename: 'MintFavorite' },
          { mint: '7dDnu7pAKNZDpU7GNUMrzKX5ZMyKkhTDB5FTfF9Jxj1y', __typename: 'MintFavorite' },
          { mint: '7f8aTVE5pq41uJrPf9TuHJnCs2x9SoZfyCqr8dbgLzUk', __typename: 'MintFavorite' },
          { mint: '7J8DWFKauRSThgfaqxXCkwJsqHck3JnQL9zti9MXyDL1', __typename: 'MintFavorite' },
          { mint: '7kHcRsVSha6A658kJnSxAXTSKyiCfqNKbpPA7ztAZV1h', __typename: 'MintFavorite' },
          { mint: '7Md4r7cvm7poHQUNdFnqLXoMCYEcTnRAXopdfyaa6MdD', __typename: 'MintFavorite' },
          { mint: '7NjLqZREE8Hu7SijDPRoiz713vgbvd1HGD6ePRNfGyTy', __typename: 'MintFavorite' },
          { mint: '7p9CED3AR9vD21crEknRbsG8E82XtaqcL3MyExB28Ysb', __typename: 'MintFavorite' },
          { mint: '7R3YcsMRhqS1HkS6xGZuz8xvvqpxJMBADkYj57Yw2ixJ', __typename: 'MintFavorite' },
          { mint: '7TayEHSG9raiP5jHsRXp5XRnEA9g6CaX2nh6DrPhKJwS', __typename: 'MintFavorite' },
          { mint: '7tSSNi3MXacwomkwDyQDn7ojMkFhDtZfzPvM2Koapris', __typename: 'MintFavorite' },
          { mint: '7VvBELQaS56uzYJA1FPsNhdhMsanrrLj4RRLTgPSTPmF', __typename: 'MintFavorite' },
          { mint: '7wvHy2rZhb2zsxaC4gFq33nGADck9Xipu9VSqKaoW88v', __typename: 'MintFavorite' },
          { mint: '7Yb7rfKWhgqqTJSSVxxn4QPUm3bC6oHrQkHxfYLWciEv', __typename: 'MintFavorite' },
          { mint: '7ZULSxm2maZtxqJTyT5utVCYuhNF3S1w4WunQqS7SPiw', __typename: 'MintFavorite' },
          { mint: '81DqXtD6UpzBWN9aR9rGHo4qcKrhw4NroXNQ1WH7KJjt', __typename: 'MintFavorite' },
          { mint: '8e7GcuyxHmDCNpYVWRB6AnyKfvNx342QwJNqjYGhMYNV', __typename: 'MintFavorite' },
          { mint: '8edfxQiGi41WwiKmD7Eja28G4koHRykS5uxNFDazz8WE', __typename: 'MintFavorite' },
          { mint: '8EqgpvMdyvHbVrc5AoVSJZkAbVBuhk19XLJN3pean2XT', __typename: 'MintFavorite' },
          { mint: '8F8aHYsEJQ67QxZjRpKE65ncETx3xYQLMNVFJ6L5qBTQ', __typename: 'MintFavorite' },
          { mint: '8FTZjuVSrQPs3mavTGLqEafEae4zne8rsZhtznn1uLMa', __typename: 'MintFavorite' },
          { mint: '8K6rUNrQFQYBUZhBigPeNPxnAvv2yf8V1RPS4AXSmJPd', __typename: 'MintFavorite' },
          { mint: '8oiD6rTQYc8iJjmASEDd9FuLiCCifpehmV2r4NrRsCo5', __typename: 'MintFavorite' },
          { mint: '8oNATHkqzMJ4qGABU9brtQeQ7QSXBBo989hFjJ84Cp1A', __typename: 'MintFavorite' },
          { mint: '8PNaCh7tTmvP7Rmpq8TJG8VfBYB48z8qK1RXEyhiTtRj', __typename: 'MintFavorite' },
          { mint: '8qBeEyMF3vKGxWkvVeYR4Zj2mCQNSX4UXBuKbMn5s9WK', __typename: 'MintFavorite' },
          { mint: '8TXei27KU1SCaSYGy18dL9o91CAdE8py74fbCjFnJPEq', __typename: 'MintFavorite' },
          { mint: '8WwuX7tjbb4nkJqSYRt6cyCib7ZhJ1UbwowCYABdMfYZ', __typename: 'MintFavorite' },
          { mint: '8ZG545WjJimeL8H8hxVZsA1tQhsvcSByMz6bF3urvZvE', __typename: 'MintFavorite' },
          { mint: '96a9BUq91jbVr8vzrFqMc8VV1ThPe2bAi9enHL9AbiQP', __typename: 'MintFavorite' },
          { mint: '995pffNUNsgqv3rXDrjZLdWBqqf5h95NfgMzCaDZ3QQu', __typename: 'MintFavorite' },
          { mint: '99qv7J9F1rJcrR4z7dT4nnYjLGWKz7UuHxXZS5tJfLGk', __typename: 'MintFavorite' },
          { mint: '9Cwm5qxNCDr1sGTBAygBZGwVEVooJ3k2w1TF3CKhqeky', __typename: 'MintFavorite' },
          { mint: '9D7KXDXfSwm1ZWWua1o8CSSZ28X9skjfqnCw9Ls3YGS8', __typename: 'MintFavorite' },
          { mint: '9gubYeA2N8NW7tp89bSK5nyy6nkqSA3AUVbbfdzbdh75', __typename: 'MintFavorite' },
          { mint: '9ieXvhRxoK35v1qDdWnae1qPBqUS76NMQJj4V6hn5xw8', __typename: 'MintFavorite' },
          { mint: '9jVQ8zdEnLsnAaY1NwHY3kFM9YL6pDrtZfSvwSa9pEBa', __typename: 'MintFavorite' },
          { mint: '9Kisgd3q9HsvHtxWGfrhZqXmRnxnzsgApDyvwUeUkwPz', __typename: 'MintFavorite' },
          { mint: '9L4juJCb7Eq8gTSkGiYhFkRrBjhMAm1JGv7QEf4j98Jw', __typename: 'MintFavorite' },
          { mint: '9m3HUVrfyhU4erM6nKRMs5LqWsHWHUn2VX2CZNWYYiTw', __typename: 'MintFavorite' },
          { mint: '9nHsjjix1r83V7kNR2eahTGNdbKBkSuRMif2QyUwCb7R', __typename: 'MintFavorite' },
          { mint: '9R21CZMCaFK7dXuJbxJNrkkj2o9Uh1sqq7nYEXDihoBK', __typename: 'MintFavorite' },
          { mint: '9SEBFxMGywB9vEBsQDPEkSPZkKsPiJWJ5Bw6bYJB9iuN', __typename: 'MintFavorite' },
          { mint: '9SKQUcWrzn1ucix54HCBeqMvKw9Ryssyuz5o8zkLP1B6', __typename: 'MintFavorite' },
          { mint: '9TcY8M5qxgKMjJBtCPzVBLXBZ1oifJG4vsePBt7i82hJ', __typename: 'MintFavorite' },
          { mint: '9tE5Vh9vmY3BQc1fWE6xLMnk4mBwsqj9R2sphFzau3Jo', __typename: 'MintFavorite' },
          { mint: '9Z74kbHpePZDKaUcL8gK4X4KMZj2AuuUUEyhYJ79j1Hw', __typename: 'MintFavorite' },
          { mint: 'A1ecM1cajbukVSpEc4BcBTWnZHNsjh5jitEBENgZ66EJ', __typename: 'MintFavorite' },
          { mint: 'A4mtW7iB6zyTrJMnKfsjZP2atCESqjbZnZuEvcyvNyFa', __typename: 'MintFavorite' },
          { mint: 'A9bpxV9xufkL9munemiSBg9FBRi1Ap67PHMf7ftquDb8', __typename: 'MintFavorite' },
          { mint: 'A9J3RT5sqRY6B8pFsUdiRG8Es5YhW6XyBDqFgR3DtTe7', __typename: 'MintFavorite' },
          { mint: 'AAgw4Em6QUJkdam38xUKUWpE9iLdh2qDoEgsCPSAos1e', __typename: 'MintFavorite' },
          { mint: 'Abs2iydUetmByDhGwov1HDc3irBEHfD2zMcCsdr8T1Nw', __typename: 'MintFavorite' },
          { mint: 'ACccKhEfePABmhf2rPg4ugoFKFUD2FXY23BQfazbTwh2', __typename: 'MintFavorite' },
          { mint: 'ACfVeaXFNHBfGNAKus84BcoBVCpKVU8AA3pF3Q8hDUdf', __typename: 'MintFavorite' },
          { mint: 'AgPHHMMFdFZww27CphHTuYWiXxyXKEUYwtyvbYjZiUC2', __typename: 'MintFavorite' },
          { mint: 'AhjgoRxV1cWzMuTdGZHPiupAS22c18pEhKGt1bWWWtG', __typename: 'MintFavorite' },
          { mint: 'Ak4eFbEMtbi6rWfZP8DDnJjuf3AwGy8v4DcS61QsWNpc', __typename: 'MintFavorite' },
          { mint: 'ALYbkELTkV4EPah6rSJSGBMWzGgGCzhJsQ7bugStMrJ8', __typename: 'MintFavorite' },
          { mint: 'AnhV2HWXX6KSdmXGkbU7V1TGv4iLnnbvnxWWd8FSZ3uM', __typename: 'MintFavorite' },
          { mint: 'Ao1tqHLrtiozZh2V7L96FvgiLqpHbfuBavnZvT1YVcb6', __typename: 'MintFavorite' },
          { mint: 'APb8LAWneaUF9NttweZW1AX68eScDykjoH26VsYyd2XY', __typename: 'MintFavorite' },
          { mint: 'ApXc5yCgkbBxipf4rFsArBYKs5wa9rFcPBMiynijdXK5', __typename: 'MintFavorite' },
          { mint: 'AqqaLo6xHTLcdoYazjN1tXDza98V1ZnRschNb9pdcK7w', __typename: 'MintFavorite' },
          { mint: 'AR2AXUnwYvsC7hcP9qWfGDtJTnURNwfrzv6YL1DtU8LZ', __typename: 'MintFavorite' },
          { mint: 'AUccjur1fSLyNN66cUuyzfm8nECB5g2DHmwF8uKZJJiM', __typename: 'MintFavorite' },
          { mint: 'AUY8BBSg32JPxQPdh33QjybBvE82VkwZgrz1fmmhMnWG', __typename: 'MintFavorite' },
          { mint: 'Aw4RhpcW5rod2Afhp7dhv2XrMZyNJpzVdYkjJ7kkYzpS', __typename: 'MintFavorite' },
          { mint: 'AwcJjdw2Kz59T4sfaiKxP4VfPqdryoLMm27E5BBphX8H', __typename: 'MintFavorite' },
          { mint: 'AwEJTPwomWxTLz75upZFgeJuKnYMAHH7PdUV7Vy4r2yz', __typename: 'MintFavorite' },
          { mint: 'AxjyH3CoMrikaxWQfCRrPT7UvcMMpQUv8vzgEGLG9is9', __typename: 'MintFavorite' },
          { mint: 'AZ3C6qYm1YcyVDwHukqNZqhAcM22ECpizNDqAkLW7HCx', __typename: 'MintFavorite' },
          { mint: 'AZgWX9Prj2wtZJdTAjPD2iLLGTTxBpqw4fGJD4inmhYk', __typename: 'MintFavorite' },
          { mint: 'BBrKUPkx9Nq4DiTFo4xgXQDiEStNo9j891oiWN9oy26G', __typename: 'MintFavorite' },
          { mint: 'BJvARjYgyK4KnEgr1kKuU8G8A5LaPRxyjZmJnN3Kkr6x', __typename: 'MintFavorite' },
          { mint: 'BKWuUJsFzMfR9LB2j4XkRnGAJzcEx1g971cVPJRg9Msu', __typename: 'MintFavorite' },
          { mint: 'BNqAYYhbo6FP5MtARB7APQmb5stqDG5paKmj1TeEkKks', __typename: 'MintFavorite' },
          { mint: 'Bu2prukCjcDYsYn9XQwebsFbTpVvYAWFREukJv6NQr3p', __typename: 'MintFavorite' },
          { mint: 'BuqcLtHebpJzvBXUykGMyvhdLGnCMuVafipxSH4qEDmH', __typename: 'MintFavorite' },
          { mint: 'bVfD9f9iofZ2v8BiuU3h4hndDuCZHLKXemc1S6phEA9', __typename: 'MintFavorite' },
          { mint: 'BWdnfRDgAMKcV5rnGhTjiqUPwX2LutL1euWynktygiWj', __typename: 'MintFavorite' },
          { mint: 'BY4VitASWmtaPmQ65mq8v4Z6fy5b3CMb7aw4V2Pn544r', __typename: 'MintFavorite' },
          { mint: 'C3rKuDsk5E7ZuKHNJZNM648gXeqeNgrDrW4vt9ezQquV', __typename: 'MintFavorite' },
          { mint: 'C5maWnwamw6YP8bsewpeogXuL2hkdyuCNLUvgg4WA6qn', __typename: 'MintFavorite' },
          { mint: 'C8aUjvMMGtDtftf4BGX2g1CSv6EmMu12NbqzMwQA6XBV', __typename: 'MintFavorite' },
          { mint: 'Cd3T8rQ3rbFEggNKewDaKZMLrsUurxG24TzMAwKNijwW', __typename: 'MintFavorite' },
          { mint: 'CdWSzXKbGKQYD8Qqi7mwkN3hvwZwzCLRHJwrFCa1VU6p', __typename: 'MintFavorite' },
          { mint: 'CE1uVDuFXzQShUGLgidzzcPr8mACCa6jzsKmRKKzVAq1', __typename: 'MintFavorite' },
          { mint: 'CFoSio3tzgpUp5JF4vjeX83Ntrewpnc9aitN4BaWyGV1', __typename: 'MintFavorite' },
          { mint: 'CJj15d9Jerd9NwjbtSy6Yhim5T9C3MgJ6KHAm9oTM5Yu', __typename: 'MintFavorite' },
          { mint: 'CjTy3X7Kmv7376acwHBQU56iThrMch1otjDLiTUMEKw9', __typename: 'MintFavorite' },
          { mint: 'CkYagkSW1y119inpDihFN28dd99Lrptpz752sAju8e5S', __typename: 'MintFavorite' },
          { mint: 'CNF2LKwa5pK8UnVQqVWYh5jfU7XqpLyCJ5mjYGQgytN7', __typename: 'MintFavorite' },
          { mint: 'CNG8WRnFwxgFLaXABqvnfmdJAaLYLepJ8dk5JJuQaDTe', __typename: 'MintFavorite' },
          { mint: 'CpYf3wvMLpQADrajotzPKtNtDx3VkpVmGcD7yDXvNYsy', __typename: 'MintFavorite' },
          { mint: 'CrXojarE5JsDuLjJfohWgWGbmw8t3PvZeUX8FcqTtZNW', __typename: 'MintFavorite' },
          { mint: 'CrYmd9aZ7k4FzSWvQ1rV7L4i4Z1hqwwfatsP9jtYwQnN', __typename: 'MintFavorite' },
          { mint: 'CwMoxZ9tebHFZfdPNku6K7Z8pA3fJwazLu8TQAFUG2Py', __typename: 'MintFavorite' },
          { mint: 'D5LRLWMrbESjkEyfxpFhEyMi6SDMt6ThcrRvgmu7bWY6', __typename: 'MintFavorite' },
          { mint: 'D5rLDTvDFwx3Zqn1K9VGuzCti7bD3VZa2DXYkMEBFs6L', __typename: 'MintFavorite' },
          { mint: 'D7DiTe6yAwak1hPd75Rn3CLHb4E18STbQZ2eGbMAi9a1', __typename: 'MintFavorite' },
          { mint: 'D7neSRiRqyXN5YQNYHioYzymFBrHBxhCex8eh2nxVLk8', __typename: 'MintFavorite' },
          { mint: 'D7yV7dtDQuAoXKiPfjEctUGvcCRSZ11VyJkqcDajFbB8', __typename: 'MintFavorite' },
          { mint: 'D98tWtT1Mpz6zxHFik2NKiScnsA6UG4LcDMQxvZr52MG', __typename: 'MintFavorite' },
          { mint: 'D9bjpNe5qR7BaAB2Azrochk7DZsyXWnAW8LfKQpTqiFG', __typename: 'MintFavorite' },
          { mint: 'DAQ2M4ftYB8b88MZDBWYuHDMHUAznkR4AwYAVSCPsraR', __typename: 'MintFavorite' },
          { mint: 'DGw9Ktxcc6GoxWzmvp56csnZ6uTSbWeoJhbxu1zDviSd', __typename: 'MintFavorite' },
          { mint: 'DHakR8StBepCYz65HVpsUqcRu5eE7hK5yA9kNMaVBpbD', __typename: 'MintFavorite' },
          { mint: 'Dhh65xAbDph8JsQUYhmFPeEVBGWZ5eFcwDB6G2riKznG', __typename: 'MintFavorite' },
          { mint: 'DqNqCuykMvXKoRHep3cKkbfLLnMyhcEisJgcVLeYz1aZ', __typename: 'MintFavorite' },
          { mint: 'DQVCA9sgnWPnaovgPJSn66KPtcv4Jo6ys2E9fnFdepp7', __typename: 'MintFavorite' },
          { mint: 'Drg3iKnKCjrRHxdoNHtpwuoCuhGoMEDfcPMHJodD35vK', __typename: 'MintFavorite' },
          { mint: 'DTyLfD9r9HAKpgdCj7UuTdzLsRPgnViZjQtH4UHbMwvM', __typename: 'MintFavorite' },
          { mint: 'DUdfXb4UF1FqJbkyvBk8uKwLRmUZkimZY3FYFNtLweC5', __typename: 'MintFavorite' },
          { mint: 'DUGLuvYFMhnhhKJEGRA5w1nwp8c5wvV36Y5R4tXtgFT4', __typename: 'MintFavorite' },
          { mint: 'DuqsDTnHTtowoeUBsMNRymuMttuAyJvhyXD36oq5HRLZ', __typename: 'MintFavorite' },
          { mint: 'DUY2ruKW4rgjDM3VXUQDqckAvqdhABqMQKn5LXn9B58a', __typename: 'MintFavorite' },
          { mint: 'DweLcnFsGAkoKNhoEWLLRQDm7E4YSGtafongp4BWdmyY', __typename: 'MintFavorite' },
          { mint: 'Dy7YNyj2tGM8i4tvkkxDQYjfUrQ3jLv7CdQsiZJDjS1S', __typename: 'MintFavorite' },
          { mint: 'DYommGito9LHYDnuaWj1cV31Hh8b1uVe2JfPd9SJVXVc', __typename: 'MintFavorite' },
          { mint: 'DyQ62q4qiDe6VpK3r1QhQFmHL6PaUFmsdrrrXHjL7ULW', __typename: 'MintFavorite' },
          { mint: 'DyUZYJMYCMNM79hQ9YuYatv8YfYGLUH9KjEECmb6JWau', __typename: 'MintFavorite' },
          { mint: 'DZnKU6dKVnVTR5J4T7SkpCndgGLoyQKXYRDCeVuVTLgC', __typename: 'MintFavorite' },
          { mint: 'E33c45SpWbsZZMwF1732z5L32kQ6JRannr4iStAKqbFr', __typename: 'MintFavorite' },
          { mint: 'E5Q6qZZXtzKmZVK5gW6kZf6WfT9PKgUK1FruKduyTtHV', __typename: 'MintFavorite' },
          { mint: 'E5q914yiV4UdXmFK9EtMhrqamDhjUR9xNTNagL7hkXwo', __typename: 'MintFavorite' },
          { mint: 'E81rf4Xyn5ojfaxKw5U8w5W9pkuxUyMZGWBkEViZfxLc', __typename: 'MintFavorite' },
          { mint: 'EaQzVhbL8Zes9CN9wjBJuciHJx8onNHBvtG53YMGd8q4', __typename: 'MintFavorite' },
          { mint: 'ECJaUwBfPuBBShSnNsSvBeSukP3NGct8VDANWVm4LXRV', __typename: 'MintFavorite' },
          { mint: 'EDkjsgL44hmHSSt1nyYtavwA2Hn4jNhZEFtCKdr2mXSd', __typename: 'MintFavorite' },
          { mint: 'EeGKan3AaDqq91YUqt9Rg2VaD5my1j1sTKNhcRC3fGDF', __typename: 'MintFavorite' },
          { mint: 'EEqaQGgEoHgcpbRvo9iMBWcv4S2nXz5fFrbSnsZH16us', __typename: 'MintFavorite' },
          { mint: 'EfE6DerUHGYKnErs1PWQnAZUf5TDssqdKQJjRYAMAcSC', __typename: 'MintFavorite' },
          { mint: 'EkVtJL7qmrTWP7MQQRSWevtWzkkJ4QovyWTChSWy8n2H', __typename: 'MintFavorite' },
          { mint: 'Enh7ts5HmxJJC9BLGVq9wKg3djg8wXGxFQ3g553WXyZg', __typename: 'MintFavorite' },
          { mint: 'ERHorMKEUGAw7hpa9BYFdZ7eSL6Hbtvat16eLZmwTx5S', __typename: 'MintFavorite' },
          { mint: 'Ett1nY6EeHG9SbPZBCDohUR5gZu3d7DWdEGqgadJTsNC', __typename: 'MintFavorite' },
          { mint: 'Eub3eLy8BYtrCsS2VGEMyoH92XM5BS7nQu7oVZmSq6FF', __typename: 'MintFavorite' },
          { mint: 'EvacGSMfrsjnhS3uUTVqffYbsaQD7qBmRYGtqBuLdp7g', __typename: 'MintFavorite' },
          { mint: 'EWfWQvuNKCp7xkyh5a1tyY4ivZqGW5hCwUfuEsuMGjut', __typename: 'MintFavorite' },
          { mint: 'EWYdR2yAnt8D3qn58atnxKZmHwRBtdeWq9x9mnw4E45e', __typename: 'MintFavorite' },
          { mint: 'F1vdvUJk3o9R1wLnSKSxZx6uP7PWcoGqYtaP4Zphh5Jx', __typename: 'MintFavorite' },
          { mint: 'F4viBfuExDjNvvrwSVgHh6QntKU7QctgaCdb3f3hn6GH', __typename: 'MintFavorite' },
          { mint: 'FCa8FMnvHMpp6ihouFcm3XqRkeNc6DKEL1U7YL1zDPwx', __typename: 'MintFavorite' },
          { mint: 'FD5wESFc6w6uSacR64VnAiVZFFv97QNCxMiNPHGWzT8p', __typename: 'MintFavorite' },
          { mint: 'FFm49PXzJckPMioYuQaFVuaH92FTPjKpQo4QbSePhV2c', __typename: 'MintFavorite' },
          { mint: 'Fh7iHmYyEfaYky9zvJb15hwdAmMxr9mdDSKJTWeBg5QR', __typename: 'MintFavorite' },
          { mint: 'FHZsz5vMvow8fKAe97sXyyKQ7KtcRcJKmqwVHwwwh5rn', __typename: 'MintFavorite' },
          { mint: 'FjbzJyfkz5Fr6G8rWCGkEYTmPP4c6oZ9nSUbbRf3LzKC', __typename: 'MintFavorite' },
          { mint: 'FJHc6mWdMEf23k1uYxCbZVACBfLHU8hxxgkH6io4M2te', __typename: 'MintFavorite' },
          { mint: 'FNP1d8WoFY5mYQCKZvwPYYnJje3gUDfyHsrpevmw63pY', __typename: 'MintFavorite' },
          { mint: 'FoJNbYEL2BsBn49a9sZTCKPm2BeyZ7v3jUn7Ne6FmNiJ', __typename: 'MintFavorite' },
          { mint: 'FP8vAVhcBiHnLtwEMzbEWEctFbJq8EqHeearWjUZjBvn', __typename: 'MintFavorite' },
          { mint: 'ft1hvSDiLCU2LKMfgGHpD7Q9AGUxyfG2fqx1x9Cy2GY', __typename: 'MintFavorite' },
          { mint: 'FVaDadbfU58SuiNzjGxcsZp5YP72rKcMxZX32cavkneH', __typename: 'MintFavorite' },
          { mint: 'FZbKQgPTGp2qHJG1Eg34qHCWu81sB6kuSewwPGT3TWGr', __typename: 'MintFavorite' },
          { mint: 'Fzg2S9DJRBHGz18b4EgwTDWDefcjR4R6H34D51QkXE2r', __typename: 'MintFavorite' },
          { mint: 'FZyfcLyPmTjAxakJsmmQvupkDUirucvP9zN8WeLAYyH6', __typename: 'MintFavorite' },
          { mint: 'G6Y2jBcVTpi5Ma1CVLmAwzM9qRCJQog6uuT7yGaqx4C1', __typename: 'MintFavorite' },
          { mint: 'G8jt1Wus3hbvjzsBA98225ACp6jL9Duk5WK6azQXVXi', __typename: 'MintFavorite' },
          { mint: 'GC2vNoyr8wffwdaNzw7RzrzjYkrvpktQjNfQUzxESFAk', __typename: 'MintFavorite' },
          { mint: 'GCjTci1kVQ9FiDkGyakZBCgJ81G7Jn273SRmdZjyhCU3', __typename: 'MintFavorite' },
          { mint: 'GJhERRuoSUKcBdkJkZjygDnwGuePhFvQgnFMccUKrrT1', __typename: 'MintFavorite' },
          { mint: 'GJKrkkgWh2HKiJYPYvc3h7dzaX9rDzcd7PX4TckEjJoo', __typename: 'MintFavorite' },
          { mint: 'GK5xDHukctHAXL867JFLM2QX5ay2KtYciR33WCGjWU7n', __typename: 'MintFavorite' },
          { mint: 'GkaFcwXNbMocpa7tDKowaqJnSeH32ox6YsehgzUddaGy', __typename: 'MintFavorite' },
          { mint: 'GnH9zutA9EE4iVkgMxtjDzYVM5pGQ9T2e2BMbpc35PUS', __typename: 'MintFavorite' },
          { mint: 'GQqenm1aH9BWyBDBQGzqvPQXgonvfCxy4AG6wjzgdDvm', __typename: 'MintFavorite' },
          { mint: 'GTrobWPoQxeQwTaaLZ9YbDV3QtPFjFLhaB1aCTfQ9j9F', __typename: 'MintFavorite' },
          { mint: 'GvCLsDEQcwP7v4FmKrsfBepfs7PWs4xgVmnPR68YQutg', __typename: 'MintFavorite' },
          { mint: 'GyjyDctKCwLL7pNMVXstFZv48B3VweVkt5qY6uyfgrNX', __typename: 'MintFavorite' },
          { mint: 'HeKSLw1yUxhWJ4pTBdN7eVS5rerXMYiyCLVzop6yyFjK', __typename: 'MintFavorite' },
          { mint: 'HfwMjcVcsx2W2NTknDG6W5ASupVKGEWCKxS2mX5fRvJp', __typename: 'MintFavorite' },
          { mint: 'HkV7e2NDVugtrNZKeZYzC6guKTCDMGFSsiWxfrgqKxms', __typename: 'MintFavorite' },
          { mint: 'HM1kd9FKoG7R1bnNbjPwS3fsyBn4NzzNnA74eJshgQBw', __typename: 'MintFavorite' },
          { mint: 'HsC76rARdy6KmBkvTWipgv8aszNuC1HGDfzhY4M7JfMB', __typename: 'MintFavorite' },
          { mint: 'HuvKCvENrtb3231bvSxnJHAQS4qoyJZbvoSAGtQUyfFf', __typename: 'MintFavorite' },
          { mint: 'HyZe6kEfXWchTMnD3GPH9MmaVn9ixVojEcZLLmTswWjy', __typename: 'MintFavorite' },
          { mint: 'J2KogXLLYFHc3SviYxgyCZZH5XdBji2j825LvEmwJfCS', __typename: 'MintFavorite' },
          { mint: 'J4BKjf2S5eGJPuhEXvoLvHqxAmh4oofFyBeqnUZPYAZ2', __typename: 'MintFavorite' },
          { mint: 'J5aUE5vPmztTctgai6TbXDdarAXUF8fUVLizqhYoSS1i', __typename: 'MintFavorite' },
          { mint: 'NKWuPZeQMkWDudRxaFgjh56xfqXEqQ7c4t4gWNAnPYK', __typename: 'MintFavorite' },
          { mint: 'Nm8mHRUZGFFFuFEpv4eDHtgKuZb2GrQTaGWi43vo4i8', __typename: 'MintFavorite' },
          { mint: 'PVQfeaqwAH3K5qHjTTndgDzHzo3bzcrJWv2bQxfmJvv', __typename: 'MintFavorite' },
          { mint: 'rUBkCNXqjaPV9bGpykUVD2LdEiRjZabWbDzdp52ovgC', __typename: 'MintFavorite' },
          { mint: 'Tadzy9ozQaxUhJmDPRWrf2FxUYhosTmbz9XjNRg4gof', __typename: 'MintFavorite' },
          { mint: 'VZptw3SPaHzUGB12mH8x6ii7kAMHHqAFP38g1NJMAtu', __typename: 'MintFavorite' },
          { mint: 'wGrk64pJHPsTKWJRD4zUWbWWpm66mzTGYsEeZejv3CF', __typename: 'MintFavorite' },
        ],
        airdropOne: null,
        airdropFour: {
          rank7d: 7268,
          rankTotal: 6416,
          wallet: 'Et6B96uSx2wSGLSdj95q1iYncpf43tTPU2mWvCv5s9Ad',
          loyalty: 100,
          __typename: 'AirdropThreeProfileStats',
        },
        loyaltyLevel: 100,
        bidNotifMinPctFloor: 0,
        airdropTwoRewards: null,
        stakedTensorians: {
          totalSupply: 10004,
          stakedSupply: 7382,
          stakedNfts: [],
          stakedLevel: 0,
          activatedLevel: 0,
          overridenLevel: null,
          nftsForNextLevel: 1,
          pfp: null,
          __typename: 'StakedTensorians',
        },
        ptsStakingTotal: 0,
        ptsStaking7d: 0,
        __typename: 'UserProfile',
      },
    },
  },
];
export type GetTensorFavNFTsForWalletReponse = typeof favNftsForWalletResult;

const favResult = [{ data: { addFavMint: '4bvaAr63dGDbomJTsMCMUgWVLyUn1ugnbGfJqoY9gQRA' } }];
export type FavTensorNFTResponse = typeof favResult;

const unfavResult = [{ data: { removeFavMint: '2e7YvoKFBFNF5XKAmLrvvBAKWgVYXzy6Gx5FvZBfuCT9' } }];
export type UnfavTensorNFTResponse = typeof unfavResult;

const userBidResult = {
  mint: {
    slug: 'shadowy_super_coder_dao',
    numMints: 9999,
    onchainId: '78UP5ismEg9697ak5wCysWXcPksa2D1httiSyz2gH1z1',
    compressed: false,
    owner: null,
    name: 'Shadowy Super Coder #5057',
    imageUri: 'https://shdw-drive.genesysgo.net/8yHTE5Cz3hwcTdghynB2jgLuvKyRgKEz2n5XvSiXQabG/5057.png',
    animationUri: null,
    metadataUri: 'https://shdw-drive.genesysgo.net/8yHTE5Cz3hwcTdghynB2jgLuvKyRgKEz2n5XvSiXQabG/5057.json',
    metadataFetchedAt: 1658449035921,
    sellRoyaltyFeeBPS: 500,
    tokenStandard: null,
    tokenEdition: null,
    attributes: [
      {
        trait_type: 'Background',
        value: 'Pink',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Base Model',
        value: 'Tan',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Desk',
        value: 'Purple Metal',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Monitor 1',
        value: 'Glitch Two',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Monitor 2',
        value: 'Glitch One',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Monitor 3',
        value: 'Jet Protocol',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Mouth',
        value: 'Purple Smile',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Hoodie',
        value: 'Captain America Hacker',
        __typename: 'Attribute',
      },
      {
        trait_type: 'Favorite Programming Language',
        value: 'Go',
        __typename: 'Attribute',
      },
    ],
    lastSale: {
      price: '75000000000',
      txAt: 1648793584000,
      __typename: 'LastSale',
    },
    accState: null,
    hidden: false,
    rarityRankHrtt: 5672,
    rarityRankStat: 5637,
    rarityRankTeam: null,
    rarityRankTn: 5652,
    __typename: 'MintWithColl',
    staked: null,
    inscription: null,
  },
  bidder: 'GpYx6NpBYkddwH7KmHhBho56K5mGghhfRdii2JrtpCDV',
  margin: '4kjmixGBr8YH58PFkMnwJGE1x98kQHd652ADrK1vFVQp',
  price: '8500000000',
  mp: 'TensorSwap',
  validFrom: 1704911756000,
  expiry: 1735247197000,
  isTopBid: null,
  reaction: null,
  __typename: 'MintBid',
};

export type TensorUserBidResult = typeof userBidResult;
export type GetTensorOffersForWalletReponse = [
  {
    data: {
      userTensorBidsV2: {
        bids: TensorUserBidResult[];
        page: {
          endCursor: {
            str: '["4000000000","AwEJTPwomWxTLz75upZFgeJuKnYMAHH7PdUV7Vy4r2yz"]';
            __typename: 'BidsCursorV2';
          };
          hasMore: true;
          __typename: 'BidsPage';
        };
        __typename: 'TensorBidsV2';
      };
    };
  },
];
